GET http://localhost:3000/api/inmuebles

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso": "C/ En medio, 14",
    "letra": "2º C",
    "extension": 113,
    "num_hab": 3,
    "alquilado": true,
    "nomb_prop": "Andrés Gómez Sánchez",
    "email": "andres_gs@gmail.com"
}

###
PUT http://localhost:3000/api/inmuebles/6465e0274d20c4072c63ef32
Content-Type: application/json

{
    "extension": 103,
    "alquilado": true
}

###
DELETE http://localhost:3000/api/inmuebles/6465e0274d20c4072c63ef32