GET http://localhost:3000/api/inmuebles

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso": "C/ Doctor Fleming, 7",
    "letra": "1º B",
    "extension": 94,
    "num_hab": 3,
    "alquilado": true,
    "nomb_prop": "Jose Miguel Correa Gómez",
    "email": "jm_correa@gmail.com"
}

###
PUT http://localhost:3000/api/inmuebles/6465ddde8c698b4239346b6a
Content-Type: application/json

{
    "extension": 103,
    "alquilado": true
}

###
DELETE http://localhost:3000/api/inmuebles/6465ddde8c698b4239346b6a